### PR TITLE
Fix discount rate conversion

### LINKED ISSUE #1289: Loans: discount rate as secs
### Description

Currently, `discount_rate` is used as the user configures it (expecting a "per sec" rate). Because all other rates are passed "per year", it is confusing to the user to transform that rates by them depending on what parameter they are writting.

Convert the rate internally to "per sec" to avoid that to the user.

*Note: breaks API in the sense that it changes how a value is interpreted on the UI side*

### PR DESCRIPTION
**Pull request by lemunozm**
# Description

Fixes #1289

## Changes and Descriptions

- Removed unused test
- Discount rate is configured "per year" but handled "per sec" internally.

*Note: breaks API in the sense that it changes how a value is interpreted on the UI side*

### CODE REVIEW

File: pallets/loans-ref/src/valuation.rs [hunk 1]
```diff
@@ -103,7 +113,7 @@ where
 {
 	pub fn is_valid(&self) -> bool {
 		match self {
-			ValuationMethod::DiscountedCashFlow(dcf) => dcf.discount_rate >= One::one(),
+			ValuationMethod::DiscountedCashFlow(_dcf) => true,
 			ValuationMethod::OutstandingDebt => true,
 		}
 	}
```
Comment (lemunozm) [inline pallets/loans-ref/src/valuation.rs:119]: No longer need this check here (always true). Not sure if removing this

File: pallets/loans-ref/src/valuation.rs [hunk 2]
```diff
@@ -76,11 +81,16 @@ impl<Rate: FixedPointNumber> DiscountedCashFlow<Rate> {
...
+		// once #1189 is merged
 		let acc_rate = checked_pow(interest_rate_per_sec, exp).ok_or(ArithmeticError::Overflow)?;
 		let ecf = acc_rate.ensure_mul_int(debt)?;
 		let ra_ecf = tel_inv.ensure_mul_int(ecf)?;
 
 		// Discount the risk-adjusted expected cash flows
+		// TODO: use InterestAccrual for this once #1189 is merged
+		// This would immply that discount_rate should be register/unregister.
 		let rate = checked_pow(self.discount_rate, exp).ok_or(ArithmeticError::Overflow)?;
 		let d = Rate::one().ensure_div(rate)?;
```
Comment (lemunozm) [inline pallets/loans-ref/src/valuation.rs:95]: I think we can get a performance boost here if using interest-accrual for this

File: pallets/loans-ref/src/valuation.rs (hunk 1 above)
Comment (mustermeiszer) [reply pallets/loans-ref/src/valuation.rs:119]: I would keep. EVen the check. Checks that interest-accrual is not doing stuff it shouldn't after we use it, right?

**Review by mustermeiszer — DISMISSED** [review]

File: pallets/loans-ref/src/valuation.rs (hunk 1 above)
Comment (lemunozm) [reply pallets/loans-ref/src/valuation.rs:119]: The check `discount_rate >= 1` needs to be removed since now we expect discount rates less than 1.

Regarding the `interest-accrual`, by now, it's not used with this rate. But when used, the own `interest-accrual` should anyways check its own values 🤷🏻‍♂️

Comment (lemunozm) [reply pallets/loans-ref/src/valuation.rs]: This comment no longer apply because now we have an upper limit

**Review by mustermeiszer — DISMISSED** [review]
