### PR TITLE
Rewards: fix initial block value

### LINKED ISSUE #1191: Liquidity rewards: Fix first `BlockNumber` value
### Which part of the code is the issue addressing?

* Addressing a bug

### Description

The `liquidity-pallet` does not work well in the initial stage when there is no value set on `EndOfEpoch`. The default `BlockNumber` returned by this storage is current, so the condition to update the epoch data is never dispatched.

This was skipped from UTs, because we are manually setting the `BlockNumber`.

### Research/based on

- Issue found in the development chain.

### PR DESCRIPTION
**Pull request by lemunozm**
# Description

Fix the initial block issue.

Fixes #1191

## Changes and Descriptions

- Remove the `System::block_number()` usage as a default storage value, because Substrate does not insert the value in the storage when the first value is fetched. This caused that each `get()` call returned the same current block number, and `on_initialize()` logic was never dispatched.
- Simplified generic usage.
- Minor docs additions.
- Adapt tests to catch the issue.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

```sh
cargo test -p pallet-liquidity-rewards
```

# Checklist:

- [x] I have added Rust doc comments to structs, enums, traits and functions
- [x] I have made corresponding changes to the documentation
- [ ] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I rebased on the latest `main` branch

### CODE REVIEW

File: pallets/liquidity-rewards/src/lib.rs [hunk 1]
```diff
@@ -55,92 +56,39 @@ pub use frame_support::{
...
-	FixedPointOperand,
-};
+use sp_runtime::{traits::Zero, FixedPointOperand};
 use sp_std::mem;
 use weights::WeightInfo;
 
-/// Type that contains the timestamp of an epoch.
-#[derive(Encode, Decode, TypeInfo, MaxEncodedLen, RuntimeDebug)]
-#[cfg_attr(test, derive(PartialEq))]
-pub struct EpochTimestamp<BlockNumber>(BlockNumber);
```
Comment (lemunozm) [inline pallets/liquidity-rewards/src/lib.rs:68]: We no longer need a custom type because now the default value doesn't need to do any computation.

File: pallets/liquidity-rewards/src/lib.rs [hunk 2]
```diff
@@ -55,92 +56,39 @@ pub use frame_support::{
...
-pub struct EpochData<BlockNumber, Balance, GroupId, Weight, MaxGroups>
-where
-	MaxGroups: Get<u32>,
-	GroupId: Ord,
-{
-	duration: BlockNumber,
-	reward: Balance,
-	weights: BoundedBTreeMap<GroupId, Weight, MaxGroups>,
+#[derive(Encode, Decode, TypeInfo, MaxEncodedLen, RuntimeDebugNoBound)]
+#[scale_info(skip_type_params(T))]
```
Comment (lemunozm) [inline pallets/liquidity-rewards/src/lib.rs:65]: A few days ago, I learned about this. It allows to use the `T: Config` generic in any type without notification to the type info that it exists, reducing a lot of generic boilerplate. For types like this, it works pretty fine.

File: pallets/liquidity-rewards/src/lib.rs [hunk 3]
```diff
@@ -299,9 +226,9 @@ pub mod pallet {
 						epoch_data.reward = changes.reward.unwrap_or(epoch_data.reward);
 						epoch_data.duration = changes.duration.unwrap_or(epoch_data.duration);
 
-						let ends_on = ends_on.ensure_add(epoch_data.duration)?;
+						let ends_on = ends_on.max(current_block).ensure_add(epoch_data.duration)?;
```
Comment (lemunozm) [inline pallets/liquidity-rewards/src/lib.rs:229]: Because now, the initial `ends_on` not uses the current block number, we need to ensure our last `ends_on` is not too old. Suppose the following scenario:
- Block 1000 => Upgrade chain with `pallet-liquidiy-rewards`, initial epoch duration: 20
- Block 1001 => `on_initialize()` is called, next ends_on is 20 + 20 = 40 (**but we wanted 1021**)
- Block 1002 => `on_initialize()` is called, next ends_on is 40 + 20 = 60
- And so on until we reach the current chain block number

**Review by lemunozm — COMMENTED** [review]
Explanation notes below

File: pallets/liquidity-rewards/src/lib.rs [hunk 4]
```diff
@@ -206,54 +154,33 @@ pub mod pallet {
 	#[pallet::generate_store(pub(super) trait Store)]
 	pub struct Pallet<T>(_);
 
+	/// Contains the timestamp in blocks when the current epochs finalized.
```
Comment (mikiquantum) [inline pallets/liquidity-rewards/src/lib.rs:157]:
```suggestion
	/// Contains the timestamp in blocks when the current epoch is finalized.
```

File: pallets/liquidity-rewards/src/lib.rs [hunk 5]
```diff
@@ -267,7 +193,7 @@ pub mod pallet {
 	#[pallet::hooks]
 	impl<T: Config> Hooks<T::BlockNumber> for Pallet<T> {
 		fn on_initialize(current_block: T::BlockNumber) -> Weight {
-			let ends_on = EndOfEpoch::<T>::get().0;
+			let ends_on = EndOfEpoch::<T>::get();
```
Comment (mikiquantum) [inline pallets/liquidity-rewards/src/lib.rs:196]: I guess in the initial call it will return the BlockNumber default of its primitive type, which should be 0, so the following comparison should be happy

**Review by mikiquantum — APPROVED** [review]
Thanks for the quick fix. I added a few informational comments. Keep in mind, that if we want to deploy this again, we will need to reset the development chain so it starts from empty storage so this logic can be triggered. Since the development runtime version was not incremented

File: pallets/liquidity-rewards/src/lib.rs [hunk 6]
```diff
@@ -206,54 +154,33 @@ pub mod pallet {
...
-			T::BlockNumber,
-			T::Balance,
-			T::GroupId,
-			T::CurrencyId,
-			T::Weight,
-			T::MaxChangesPerEpoch,
-		>,
-		ValueQuery,
-	>;
+	pub(super) type NextEpochChanges<T: Config> = StorageValue<_, EpochChanges<T>, ValueQuery>;
```
[the remark this answers is not in the document]
Comment (lemunozm) [reply pallets/liquidity-rewards/src/lib.rs:174]: Not because `#[scale_info(skip_type_params(T))]` skip that 😃

File: pallets/liquidity-rewards/src/lib.rs (hunk 5 above)
Comment (lemunozm) [reply pallets/liquidity-rewards/src/lib.rs:196]: Yes, default `BlockNumber` is  `zero()`

File: pallets/liquidity-rewards/src/lib.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (lemunozm) [reply pallets/liquidity-rewards/src/lib.rs:174]: Also, `Config` (or any generic bound) contains only information at compile time. It never increments the size of the objects

[the remark this answers is not in the document]
Comment (wischli) [reply pallets/liquidity-rewards/src/lib.rs:174]: Im a bit late to the party but wanted to share that even though the current design is leaner, Substrate actually recommends to use the former, e.g., to specifically declare all required generic parameters instead of pulling from the Config. I suppose one argument is that its a bit more opaque. Couldn't quickly find the PR with the comment about that. The skip macro resulted just from the inconvenience that the compiler else throws when pulling from the Config. 

Definitely no need to change this now but good to keep it in mind for the future and other parts of the code we touch. Or do you disagree @lemunozm ?

[the remark this answers is not in the document]
Comment (lemunozm) [reply pallets/liquidity-rewards/src/lib.rs:174]: If you finally find that thread I would be happy to read it! Thanks for sharing this.

From my understanding of this, I think that if the type is (or should) be agnostic of the pallet, it shouldn't make use of `<T: Config>`, because it comes with the whole pallet dependency. But sometimes, the type is closely related to the pallet, and it contains a lot of types specified in it. Not using `<T: Config>` in that case adds a lot of boilerplate that seems like it's not really needed and difficult refactors and readability. Anyways, I do not have a strong thought about where to put the frontier between one decision or the other.

P.S: I took as a reference the Substrate's `nomination-pools` pallet where high-level types use `<T: Config>` and low-level types define the generics individually.
