### PR TITLE
Fix: Limitations of Transfer Allowlist

### LINKED ISSUE #1679: fix: pallet-transfer-allowlist filters
### Description
`pallet-transfer-allowlist` currently works as follows:
* no-restriction set &rarr; all receiving addresses for a transfer are valid
* restriction set for a currency &rarr; only allowed receivers are valid receivers, all other receiver will fail
    * all OTHER currencies ARE NOT restricted 

BUT it should rather be
* no-restriction set &rarr; all receiving addresses for a transfer are valid
* restriction set for a currency &rarr; only allowed receivers are valid receivers, all other receiver will fail
    * all OTHER currencies ARE restricted 

### Research/based on
This is an issue that got lost in the weeds of communicating requirements and technical specs.

### What are foreseen obstacles or hurdles to overcome?
* Storage is not made for this
* Need to adapt existing filters in runtime common

### PR DESCRIPTION
**Pull request by mustermeiszer**
# Description
See issue also. The main problem is that `pallet-transfer-allowlist` in our current setup does not allow to allow a single account to have permissions for all current and future currencies in one run. This gets problematic, as we are adding more foreign domains with currencies to the system in the future, and our pool admins are not protected to mistakenly send tokens there.

Furthermore, previously, we had not idea of how to restrict native transfers. 

Fixes #1679

## Changes and Descriptions
* Remove `NativeCurrency` from `pallet-transfer-allowlist`
* Introduces `PreBalanceTransferExtension` 
   - a `SignedExtension` that will block any calls of `pallet-balances` that transfer `CFG` if they should no go from `send` to `recv`
   - this is the only viable solution - BUT error resolution is bad, as we are not working with `DispatchErrors` on that level (see discussion [here](https://github.com/paritytech/polkadot-sdk/issues/2563))
* Introduces the `FilterCurrency` enum that represents an allowance for `All` currencies or just for `Specific` one
* Adapts filters in `runtime-common` to actually take into account the usage of `FilterCurrency`

# Checklist:
- [x] I have added Rust doc comments to structs, enums, traits and functions
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: runtime/altair/src/lib.rs [hunk 1]
```diff
@@ -1960,7 +1960,7 @@ mod __runtime_api_use {
 #[cfg(not(feature = "disable-runtime-api"))]
 use __runtime_api_use::*;
 use cfg_types::locations::Location;
-use runtime_common::transfer_filter::PreNativeTransfer;
+use runtime_common::transfer_filter::{FilterCurrency, PreNativeTransfer};
```
Comment (lemunozm) [inline runtime/altair/src/lib.rs:1963]: Wondering if this could incur in any migration

File: runtime/common/src/transfer_filter.rs [hunk 2]
```diff
@@ -13,32 +13,47 @@
...
+				sender.clone(),
 				Location::XCM(BlakeTwo256::hash(&destination.encode())),
-				currency,
+				FilterCurrency::Specific(currency),
 			)
+			.or(T::allowance(
+				sender,
+				Location::XCM(BlakeTwo256::hash(&destination.encode())),
+				FilterCurrency::All,
+			))
```
Comment (lemunozm) [inline runtime/common/src/transfer_filter.rs:56]: A couple of points:
 1. I'm pretty sure the right side of the `or()` is computed before checking whether the left side is true. I think you want here `or_else()` which takes a closure.
 2. If the first is false, and then we check for `FilterCurrency::All`. Is it not the same as just checking it for `FilterCurrency::All`?

File: runtime/common/src/transfer_filter.rs [hunk 3]
```diff
@@ -121,24 +136,111 @@ impl<
...
+			t.send.clone(),
+			Location::Local(t.recv.clone()),
+			FilterCurrency::Specific(t.id),
+		)
+		.is_ok() || T::allowance(
+			t.send.clone(),
+			Location::Local(t.recv.clone()),
+			FilterCurrency::All,
+		)
+		.is_ok()
```
Comment (lemunozm) [inline runtime/common/src/transfer_filter.rs:155]: Same as above, point 2.

File: runtime/common/src/transfer_filter.rs [hunk 4]
```diff
@@ -121,24 +136,111 @@ impl<
...
+		T::allowance(
+			sender.clone(),
+			Location::Address(receiver.clone()),
+			FilterCurrency::Specific(currency),
+		)
+		.or(T::allowance(
+			sender,
+			Location::Address(receiver),
+			FilterCurrency::All,
+		))
```
Comment (lemunozm) [inline runtime/common/src/transfer_filter.rs:176]: Same as above, points 1. and 2.

File: runtime/common/src/transfer_filter.rs [hunk 5]
```diff
@@ -121,24 +136,111 @@ impl<
...
+		pallet_transfer_allowlist::pallet::Pallet::<T>::allowance(
+			who.clone(),
+			Location::Local(recv.clone()),
+			FilterCurrency::All,
+		)
+		.or(pallet_transfer_allowlist::pallet::Pallet::<T>::allowance(
+			who.clone(),
+			Location::Local(recv.clone()),
+			FilterCurrency::Specific(CurrencyId::Native),
+		))
```
Comment (lemunozm) [inline runtime/common/src/transfer_filter.rs:243]: Same as above, points 1. and 2.

File: runtime/altair/src/lib.rs [hunk 6]
```diff
@@ -1715,11 +1715,10 @@ impl pallet_order_book::Config for Runtime {
 }
 
 impl pallet_transfer_allowlist::Config for Runtime {
-	type CurrencyId = CurrencyId;
+	type CurrencyId = FilterCurrency;
```
Comment (lemunozm) [inline runtime/altair/src/lib.rs:1718]: `Currency` is used in `pallet_transfer_allowlist` storages, so this would need migration. Is this pallet already used in centrifuge?

**Review by lemunozm — COMMENTED** [review]
More simple now!

Just a few comments

File: runtime/common/src/transfer_filter.rs (hunk 2 above)
Comment (mustermeiszer) [reply runtime/common/src/transfer_filter.rs:56]: Good point. Will refactor

**Comment by mustermeiszer** [comment]
Try-runtime against centrifuge: 

```
2024-01-17 16:40:28 TransferAllowlist-CurrencyMigration:  PRE UPGRADE: Starting...    
2024-01-17 16:40:28 TransferAllowlist-CurrencyMigration:  Counted 2 keys in old allowance storage.    
2024-01-17 16:40:28 TransferAllowlist-CurrencyMigration:  Counted 2 keys in old delay storage.    
2024-01-17 16:40:28 TransferAllowlist-CurrencyMigration:  Migrating currency used started...    
2024-01-17 16:40:28 TransferAllowlist-CurrencyMigration:  POST UPGRADE: Starting...    
2024-01-17 16:40:28 TransferAllowlist-CurrencyMigration:  POST UPGRADE: Finished. 
```

File: runtime/altair/src/lib.rs (hunk 6 above)
Comment (mustermeiszer) [reply runtime/altair/src/lib.rs:1718]: Done in https://github.com/centrifuge/centrifuge-chain/pull/1693/commits/fc621f78c18b752c31f319e4584568ffed8a394c

File: runtime/common/src/transfer_filter.rs (hunk 2 above)
Comment (mustermeiszer) [reply runtime/common/src/transfer_filter.rs]: Done in https://github.com/centrifuge/centrifuge-chain/pull/1693/commits/13906f416fa726d553fdc41c5ac7ea70124afcba

File: runtime/common/src/transfer_filter.rs [hunk 7]
```diff
@@ -13,32 +13,49 @@
...
 use xcm::v3::{MultiAsset, MultiLocation};
 
+#[derive(
+	Clone, Copy, PartialOrd, Ord, PartialEq, Eq, Debug, Encode, Decode, TypeInfo, MaxEncodedLen,
+)]
+pub enum FilterCurrency {
+	All,
+	Specific(CurrencyId),
+}
+
```
Comment (lemunozm) [inline runtime/common/src/transfer_filter.rs:35]: I am still confusing about the second point: 

> If the first is false, and then we check for `FilterCurrency::All`. Is it not the same as just checking it for `FilterCurrency::All`?

Maybe would help adding docs here?

Comment (mustermeiszer) [reply runtime/common/src/transfer_filter.rs:35]: where did I write that line? ^^

Comment (mustermeiszer) [reply runtime/common/src/transfer_filter.rs:35]: Logically, you can set
* an allowance for an account to be allowed for ALL currencies
* an allowance for an account to be allowed to ONE currency

There might be an overlap if you set account `A` both for `All` and for `Specific(CURRENCY)`. Do you want to prevent that? 
Preventing the other way around is harder, as It would need to iterate over the whole storage of that account.

Comment (lemunozm) [reply runtime/common/src/transfer_filter.rs:35]: > where did I write that line? ^^

I wrote it 😆

Ok, I think I follow you now 👍🏻, thanks!

**Review by lemunozm — DISMISSED** [review]
Good work with the migration! 🙌🏻 LGTM

File: runtime/common/src/migrations/transfer_allowlist_currency.rs [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+const LOG_PREFIX: &str = "TransferAllowlist-CurrencyMigration: ";
+
+struct DelayPrefix;
+impl StorageInstance for DelayPrefix {
+	const STORAGE_PREFIX: &'static str = "AccountCurrencyTransferCountDelay";
+
+	fn pallet_prefix() -> &'static str {
+		"TransferAllowList"
+	}
+}
```
Comment (lemunozm) [inline runtime/common/src/migrations/transfer_allowlist_currency.rs:40]: Out of curiosity, did you try `#[pallet::storage_prefix = "foo"]` this?

Comment (mustermeiszer) [reply runtime/common/src/migrations/transfer_allowlist_currency.rs:40]: No, you wrote me too late. ^^ 

I think I will keep for now, as I am not sure, how to add the pallet-prefix with this macro. and lazy to change the code. We will remove it anyways afterwards.

File: runtime/common/src/transfer_filter.rs [hunk 9]
```diff
@@ -175,23 +172,32 @@ impl<T: TransferAllowance<AccountId, CurrencyId = FilterCurrency, Location = Loc
...
+	pub fn new() -> Self {
+		PreBalanceTransferExtension(sp_std::marker::PhantomData::default())
+	}
+}
+
+impl<T: frame_system::Config> sp_std::fmt::Debug for PreBalanceTransferExtension<T> {
+	fn fmt(&self, f: &mut Formatter<'_>) -> sp_std::fmt::Result {
+		f.debug_struct("PreBalanceTransferExtension").finish()
+	}
+}
```
Comment (lemunozm) [inline runtime/common/src/transfer_filter.rs:189]: Maybe you were looking for the derive `RuntimeDebugNoBound` (?)

File: runtime/integration-tests/src/generic/cases/liquidity_pools.rs [hunk 10]
```diff
@@ -219,22 +219,22 @@ pub mod utils {
 	}
 
 	pub fn ausd(amount: Balance) -> Balance {
-		amount * dollar(currency_decimals::AUSD)
+		amount * decimals(currency_decimals::AUSD)
```
Comment (lemunozm) [inline runtime/integration-tests/src/generic/cases/liquidity_pools.rs:222]: 👌🏻

File: runtime/integration-tests/src/generic/cases/liquidity_pools.rs [hunk 11]
```diff
@@ -8899,12 +8901,141 @@ mod centrifuge {
...
+		fn restrict_all<T: Runtime>() {
+			let mut env = RuntimeEnv::<T>::from_parachain_storage(
+				Genesis::default()
+					.add(genesis::balances::<T>(cfg(TRANSFER_AMOUNT + 10)))
+					.add(orml_tokens::GenesisConfig::<T> {
+						balances: vec![(
+							Keyring::Alice.to_account_id(),
+							USDC,
+							T::ExistentialDeposit::get() + usdc(TRANSFER_AMOUNT),
+						)],
```
Comment (lemunozm) [inline runtime/integration-tests/src/generic/cases/liquidity_pools.rs:8921]: I think there is already a one line utility for just this in `genesis` module

**Review by lemunozm — DISMISSED** [review]
Minor optional comments, but LGTM!

File: runtime/common/src/migrations/transfer_allowlist_currency.rs [hunk 12]
```diff
@@ -0,0 +1,154 @@
...
+		OldAccountCurrencyTransferAllowance::translate::<AllowanceDetails<BlockNumber>, _>(
+			|(account, currency_id, location), allowance| {
+				pallet_transfer_allowlist::AccountCurrencyTransferAllowance::<T>::insert(
+					(account, FilterCurrency::Specific(currency_id), location),
+					allowance,
+				);
+
+				counter += 1;
+				// We will remove the storage here, as we are inserting the new storage above
+				None
```
Comment (wischli) [inline runtime/common/src/migrations/transfer_allowlist_currency.rs:93]: NIT: Interesting approach 🙃 Dealt with this yesterday as well. A cleaner way would be to translate `pallet_transfer_allowlist::AccountCurrencyTransferAllowance::<T>::translate::<AllowanceDetails<BlockNumber>, _>` to reduce the number of writes by `counter`.

File: runtime/common/src/migrations/transfer_allowlist_currency.rs [hunk 13]
```diff
@@ -0,0 +1,154 @@
...
+		T: pallet_transfer_allowlist::Config<
+			AccountId = AccountId,
+			Location = Location,
+			CurrencyId = FilterCurrency,
+			BlockNumber = BlockNumber,
+		>,
+	> OnRuntimeUpgrade for Migration<T>
+{
+	fn on_runtime_upgrade() -> Weight {
+		log::info!("{LOG_PREFIX} Migrating currency used started...");
```
Comment (wischli) [inline runtime/common/src/migrations/transfer_allowlist_currency.rs:82]: NIT: Since this is a breaking storage change, we should bump the `StorageVersion` of `pallet-transfer-allowlist` and check versions. Normally, I would have flagged this as `CR` but no reason to be that pedantic here for the sake of the 1025 deadline.

**Review by wischli — COMMENTED** [review]
Two non-blocking comments. Thanks for working on this!

File: runtime/common/src/migrations/transfer_allowlist_currency.rs (hunk 12 above)
Comment (mustermeiszer) [reply runtime/common/src/migrations/transfer_allowlist_currency.rs:93]: Curious. I thought about using `translate` but I need to change the `Key` and not the `Value`. Is this possible with translate?

File: runtime/common/src/migrations/transfer_allowlist_currency.rs (hunk 13 above)
Comment (mustermeiszer) [reply runtime/common/src/migrations/transfer_allowlist_currency.rs:82]: Will still do.

File: runtime/integration-tests/src/generic/cases/liquidity_pools.rs (hunk 11 above)
Comment (mustermeiszer) [reply runtime/integration-tests/src/generic/cases/liquidity_pools.rs:8921]: Yeah, but that does not work well with the new `add(..)` logic here.

File: runtime/common/src/transfer_filter.rs (hunk 9 above)
Comment (mustermeiszer) [reply runtime/common/src/transfer_filter.rs:189]: Nice.

File: runtime/common/src/migrations/transfer_allowlist_currency.rs (hunk 12 above)
Comment (wischli) [reply runtime/common/src/migrations/transfer_allowlist_currency.rs:93]: Sorry, didn't catch the key change. In this case, `translate` cannot be used as it only provides means of altering values.

File: runtime/common/src/migrations/transfer_allowlist_currency.rs (hunk 13 above)
Comment (mustermeiszer) [reply runtime/common/src/migrations/transfer_allowlist_currency.rs:82]: Changed

**Comment by mustermeiszer** [comment]
I also tested signing transactions via Polkadot-js just now. Works all fine.

**Review by lemunozm — DISMISSED** [review]

**Review by wischli — COMMENTED** [review]
Unfortunately, I have a pedantic simple change request. Apart from that, looks great! Also tested the migration, works like a charm!

**Review by wischli — DISMISSED** [review]

File: runtime/integration-tests/src/generic/envs/runtime_env.rs [hunk 14]
```diff
@@ -92,7 +96,18 @@ impl<T: Runtime> Env<T> for RuntimeEnv<T> {
 			utils::create_extrinsic::<T>(who, call, nonce)
 		});
 
-		self.parachain_state_mut(|| T::Api::apply_extrinsic(extrinsic).unwrap())?;
+		self.parachain_state_mut(|| {
+			let res = T::Api::apply_extrinsic(extrinsic);
+			// NOTE: This is our custom error that we are having in the
+			//       `PreBalanceTransferExtension` SignedExtension, so we need to
+			//        catch that here.
+			if let Err(TransactionValidityError::Invalid(InvalidTransaction::Custom(255))) = res {
```
Comment (lemunozm) [inline runtime/integration-tests/src/generic/envs/runtime_env.rs:104]: Does `255` come from any constant defined somewhere else, or is it random?

File: runtime/integration-tests/src/generic/envs/runtime_env.rs [hunk 15]
```diff
@@ -101,7 +116,9 @@ impl<T: Runtime> Env<T> for RuntimeEnv<T> {
 				}
 				_ => None,
 			})
-			.unwrap();
+			// NOTE: This is actually not always correct. Even if there is not fee event, there is a
+			//       fee substracted if the `pre_dispatch()` errors out.
```
Comment (lemunozm) [inline runtime/integration-tests/src/generic/envs/runtime_env.rs:120]: Is there any way to get that value from `pre_dispatch()`?

File: runtime/integration-tests/src/generic/cases/liquidity_pools.rs [hunk 16]
```diff
@@ -2002,7 +2002,7 @@ mod development {
 
 				env.parachain_state_mut(|| {
 					let pool_id = DEFAULT_POOL_ID;
-					let amount = 10 * dollar(12);
+					let amount = 10 * decimals(12);
```
Comment (lemunozm) [inline runtime/integration-tests/src/generic/cases/liquidity_pools.rs:2005]: @William maybe you can cherry-pick the commit that introduces these changes to avoid a lot of conflicts in your liquidity-pools tests refactor

File: runtime/integration-tests/src/generic/envs/runtime_env.rs [hunk 17]
```diff
@@ -92,7 +96,18 @@ impl<T: Runtime> Env<T> for RuntimeEnv<T> {
 			utils::create_extrinsic::<T>(who, call, nonce)
 		});
 
-		self.parachain_state_mut(|| T::Api::apply_extrinsic(extrinsic).unwrap())?;
+		self.parachain_state_mut(|| {
+			let res = T::Api::apply_extrinsic(extrinsic);
+			// NOTE: This is our custom error that we are having in the
+			//       `PreBalanceTransferExtension` SignedExtension, so we need to
+			//        catch that here.
```
Comment (lemunozm) [inline runtime/integration-tests/src/generic/envs/runtime_env.rs:103]: Why are we having this error? Should we configure something to avoid generating this error?

**Review by lemunozm — APPROVED** [review]
Some questions, but LGTM

File: runtime/integration-tests/src/generic/envs/runtime_env.rs (hunk 15 above)
Comment (mustermeiszer) [reply runtime/integration-tests/src/generic/envs/runtime_env.rs:120]: You mean the fee amount? do not think so.

File: runtime/integration-tests/src/generic/envs/runtime_env.rs (hunk 14 above)
Comment (mustermeiszer) [reply runtime/integration-tests/src/generic/envs/runtime_env.rs:104]: Random

File: runtime/integration-tests/src/generic/envs/runtime_env.rs (hunk 17 above)
Comment (mustermeiszer) [reply runtime/integration-tests/src/generic/envs/runtime_env.rs:103]: The `PreBalancesTransferExtension` is filtering out all calls that are `pallet-balances::Transfer*` alike calls, if there is a restriction set and the receiver is not correct. So i.e. the filter for native currency. 

But it is not working on the DispatchError level, but on the validity level, so we can not return the correct errors.

File: runtime/common/src/transfer_filter.rs [hunk 18]
```diff
@@ -231,18 +236,53 @@ where
...
+		// There is NO allowance set for `All`
+		(Ok(None), Ok(None)) => Ok(()),
+		// There is an allowance set for `Specific(id)`, for the given recv
+		// There is NO allowance set for `All`
+		(Ok(Some(_)), Ok(None)) => Ok(()),
+		// There is NO allowance set for `Specific(id)`
+		// There is an allowance set for `All`, for the given recv
+		(Ok(None), Ok(Some(_))) => Ok(()),
+	}
+}
```
Comment (lemunozm) [inline runtime/common/src/transfer_filter.rs]: I think there is a common factor here. If there is no `Err` or there is some `Some`, then `Ok` else `Err`, but not sure if you prefer to leave it explicitly.

File: runtime/integration-tests/src/generic/envs/runtime_env.rs (hunk 17 above)
Comment (lemunozm) [reply runtime/integration-tests/src/generic/envs/runtime_env.rs:103]: Ok, thanks for the explanation

Comment (lemunozm) [reply runtime/integration-tests/src/generic/envs/runtime_env.rs:103]: So, even if such an error is dispatched, the extrinsic is considered submitted, right?

Comment (mustermeiszer) [reply runtime/integration-tests/src/generic/envs/runtime_env.rs:103]: yes.

File: runtime/common/src/transfer_filter.rs (hunk 18 above)
Comment (lemunozm) [reply runtime/common/src/transfer_filter.rs]: Sure!

**Review by lemunozm — APPROVED** [review]
