### PR TITLE
Rewards: All-in test. Fix gap movement

### LINKED ISSUE #1143: Rewards: Gap mechanism all-in test

### PR DESCRIPTION
**Pull request by lemunozm**
# Description

This PR adds a complex test for the gap reward mechanism.

Fixes #1143

## Changes and Descriptions
- Minor test constant renamed.
- Add a complex unitary test for this the gap mechanism:
```
A,B => Users
X,Y,Z,M => Currencies
Dx => Distributions
Gx => Groups

        D0     |     D1    |          D2           |     D3    |    D4    |  D5
 G1 -----------------------------------------------------------------------------
     Stake X A | Stake Z A | MOVE Z ·              | Stake M A | MOVE X · |
               |           |        ·              |           |        · |
               |           |        v              |           |        v |
 G2 -----------------------------------------------------------------------------
     Stake Y B |           |         Unstake Z A/2 |           |          |
```

- Fix gap mechanism implementation with a movement issue found in this test.
 
## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

```sh
cargo test -p pallet-rewards
```

# Checklist:

- [x] I have added Rust doc comments to structs, enums, traits and functions
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I rebased on the latest `main` branch

### CODE REVIEW

File: pallets/rewards/src/tests.rs [hunk 1]
```diff
@@ -70,5 +70,127 @@ mod mechanism {
...
+		//        D0     |     D1    |          D2           |     D3    |    D4    |  D5
+		// G1 -----------------------------------------------------------------------------
+		//     Stake X A | Stake Z A | MOVE Z ·              | Stake M A | MOVE X · |
+		//               |           |        ·              |           |        · |
+		//               |           |        v              |           |        v |
+		// G2 -----------------------------------------------------------------------------
+		//     Stake Y B |           |         Unstake Z A/2 |           |          |
+		//
+		#[test]
+		fn all_in() {
```
Comment (mikiquantum) [inline pallets/rewards/src/tests.rs:87]: 👍

**Review by mikiquantum — APPROVED** [review]

**Review by mikiquantum — APPROVED** [review]
🙏

**Review by mikiquantum — APPROVED** [review]
