### PR TITLE
Fix doc warnings

### LINKED ISSUE #1161: Docs without warnings
### Which part of the code is the issue addressing?

- Documentation

### Description

Currently, docs are built with several warning errors.

We should: 
- [ ] Fix the issues: https://github.com/centrifuge/centrifuge-chain/pull/1162
- [ ] Ensure automatically no more warnings appears (CI job checking this): https://github.com/centrifuge/centrifuge-chain/pull/1162

### How will this affect the code base

- Improve user experience reading docs.
- Gives more "quality feeling" to the project.

### What are forseen obstacles or hurdles to overcome?

Modify our CI job to force us to keep healthy docs. Can it add more time to the job pipeline? Does it reduce the development process?

### PR DESCRIPTION
**Pull request by lemunozm**
# Description

Fix doc issues that generate warnings when do `cargo doc`.

Fixes #1161

## Changes and Descriptions

- Fix doc issues.
- Removed some duplicated/unused docs.
- Force CI docs to fail if a doc warning is found.

## Type of change

- Documentation
- CI job

# How Has This Been Tested?

```sh
RUSTDOCFLAGS="-D warnings" cargo doc
```

# Checklist:

- [x] I have added Rust doc comments to structs, enums, traits and functions
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I rebased on the latest `main` branch

### CODE REVIEW

File: libs/primitives/src/lib.rs [hunk 1]
```diff
@@ -237,10 +237,6 @@ pub mod constants {
 	/// % of fee addressed to the Treasury. The reminder % will be for the block author.
 	pub const TREASURY_FEE_RATIO: Perbill = Perbill::from_percent(80);
 
-	/// Represents the protobuf encoding - "NFTS". All Centrifuge documents are formatted in this way.
-	/// These are pre/appended to the registry id before being set as a [RegistryInfo] field in [create_registry].
-	pub const NFTS_PREFIX: &[u8] = &[1, 0, 0, 0, 0, 0, 0, 20];
```
Comment (lemunozm) [inline libs/primitives/src/lib.rs:242]: I've removed this because seems unused. Double-check this, please!

File: pallets/claims/src/lib.rs [hunk 2]
```diff
@@ -34,24 +34,6 @@
 //! ### Supported Origins
 //! Valid origin is an administrator or root.
 //!
-//! ### Types
```
Comment (lemunozm) [inline pallets/claims/src/lib.rs:37]: Removed because it is automatically generated by cargo doc

File: .github/workflows/docs.yml [hunk 3]
```diff
@@ -7,6 +7,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       RUST_TOOLCHAIN: "nightly-2022-08-05"
+      RUSTDOCFLAGS: "-D warnings"
```
Comment (lemunozm) [inline .github/workflows/docs.yml:10]: Not sure if the docs CI job is only run when a commit is successfully merged. If so, a commit can be merged, and then the doc job fails. Not sure if this is the expected behavior we want. Can you confirm this @gpmayorga ? I would expect that a commit with bad documentation can not be merged, but this would increase the CI time for each PR.

File: pallets/anchors/src/lib.rs [hunk 4]
```diff
@@ -66,7 +66,7 @@ type BalanceOf<T> =
 /// This is the maximum expected time for document consensus to take place between a pre-commit of an anchor and a
 /// commit to be received for the pre-committed anchor. Currently we expect to provide around 80 mins for this.
 /// Since our current block time as per chain_spec.rs is 6s, we set this to 80 * 60 secs / 6 secs/block = 800 blocks.
-const PRE_COMMIT_EXPIRATION_DURATION_BLOCKS: u32 = 800;
+pub const PRE_COMMIT_EXPIRATION_DURATION_BLOCKS: u32 = 800;
```
Comment (mustermeiszer) [inline pallets/anchors/src/lib.rs:69]: Why?

**Review by mustermeiszer — COMMENTED** [review]
Docs look good. Don't wanna approve till @gpmayorga gives feedback regarding the CI.

File: pallets/anchors/src/lib.rs (hunk 4 above)
Comment (lemunozm) [reply pallets/anchors/src/lib.rs:69]: It is referred from a public doc, as a value the user should know. Or we do this or we need to rewrite how to explain that to the user from `pre_commit()` docs without referring this const

**Review by gpmayorga — APPROVED** [review]
Looking good, the check should be red if the cargo command fails and a message will appear in the workflow Actions page. 
If we want it to block PRs we should add it to the branch protection under "settings"

**Comment by gpmayorga** [comment]
@lemunozm we're ready for this one although with the codeowners file you'll need everyone to  approve

**Review by mustermeiszer — APPROVED** [review]
Reapproving

**Comment by mustermeiszer** [comment]
@lemunozm go ahead and merge if you want!

**Comment by lemunozm** [comment]
Thanks @gpmayorga for all your work put here 🚀
