### PR TITLE
Use 27-bit fixed point for tranche interest rates

### LINKED ISSUE #558: Use 27 decimals for interest rates on lender side

### PR DESCRIPTION
**Pull request by branan**
This also stores the interest rate in a different fixed format which
avoids some redudant conversionss for every interest calculation

Fixes #558

### CODE REVIEW

File: pallets/tinlake-investor-pool/src/tests.rs [hunk 1]
```diff
@@ -316,7 +316,7 @@ fn epoch() {
 		let pool = TinlakeInvestorPool::pool(0).unwrap();
 		assert_eq!(
 			pool.tranches[0].interest_per_sec,
-			Perquintill::from_parts(000000003170979198)
+			Rate::from_inner(1_000000003170979198376458650)
```
Comment (mustermeiszer) [inline pallets/tinlake-investor-pool/src/tests.rs:319]: Where is the number coming from?

**Review by mustermeiszer — APPROVED** [review]
LGTM!

File: pallets/tinlake-investor-pool/src/tests.rs (hunk 1 above)
Comment (branan) [reply pallets/tinlake-investor-pool/src/tests.rs:319]: This is 10% annual interest rate divided by (365 days * 24 hours * 60 minutes * 60 seconds).

The changes from the old test here are:
* Nine more digits of precision
* Adding a one to the front in storage, since previously the first thing we did when reading from storage was add 1
