### PR TITLE
lp-gateway: Add queue for outbound messages

### LINKED ISSUE #1694: Feat: Implement Queue Logic for Outbound-Queue
### Description
The main reason we need this feature is that for some code-paths, `FI` will get triggered with the following path
* Incoming message via `EVM`
* Processing of message from `FI`
* FI sends an outbound message
* Gateway enters `EVM` to send messages

This triggers a `Error::Reentrancy` on the `pallet-evm`. Although, we do not enable this feature, a dependency does and so we are exposed to that. [See](https://kflabs.slack.com/archives/C04GJQAM9P0/p1705409380219429)

#### Idea
The idea is to use an actual queue for the outbound logic. This queue will queue outgoing messages. This in between step allows to prevent a reentrancy. 
For the MvP the queue should simply use on-idle to process messages and also provide an additional extrinsic to manually process messages.

### Research/based on
* Conversation [here](https://kflabs.slack.com/archives/C04GJQAM9P0/p1705409380219429) after problems with reducing investments

### How will this affect the code base
* Increase complexity as there will be an (possibly) automated step to further forward messages to another domain
* Reduce weight of single call logic for `FI`
* Fix bug as described above

### What are foreseen obstacles or hurdles to overcome?
None so far.

### PR DESCRIPTION
**Pull request by cdamian**
# Description

Fixes #1694 

## Changes and Descriptions

- Added storage for outbound messages.
- Added `on-idle` hook logic for processing outbound messages.
- Added `DispatchResultWithPostInfo` to routers for retrieving weight.
- Added storage for failed outbound messages.
- Added extrinsics for manually executing messages.

# Checklist:

- [x] I have added Rust doc comments to structs, enums, traits and functions
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 1]
```diff
@@ -174,6 +192,19 @@ pub mod pallet {
...
+	pub(crate) type OutboundMessageQueue<T: Config> = StorageNMap<
+		_,
+		(
+			NMapKey<Blake2_128Concat, Domain>,
+			NMapKey<Blake2_128Concat, T::AccountId>,
+			NMapKey<Blake2_128Concat, T::Message>,
+		),
+		(),
+		ValueQuery,
+	>;
```
Comment (lemunozm) [inline pallets/liquidity-pools-gateway/src/lib.rs:206]: Q: Why is the message part of the key instead of the value?

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 2]
```diff
@@ -462,6 +500,65 @@ pub mod pallet {
...
+				weight_used = weight_used.saturating_add(weight);
+
+				if weight_used.all_gte(max_weight) {
+					break;
+				}
+			}
+
+			for entry in processed_entries {
+				OutboundMessageQueue::<T>::remove(entry);
+			}
```
Comment (lemunozm) [inline pallets/liquidity-pools-gateway/src/lib.rs:558]: Good point removing out from the iteration!

**Review by lemunozm — COMMENTED** [review]
LGTM!

Just a question

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 1 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:206]: If we were to use a double map with k1: domain, k2: sender, we would then need to keep a vector of messages. I wanted to avoid doing that and having to mingle with that vector every time we process something. This approach is also easier to iterate on IMO.

File: pallets/liquidity-pools-gateway/routers/src/lib.rs [hunk 3]
```diff
@@ -257,7 +253,10 @@ where
 			true,
 		)?;
 
-		Ok(())
+		Ok(PostDispatchInfo {
+			actual_weight: Some(self.xcm_domain.overall_weight),
```
Comment (cdamian) [inline pallets/liquidity-pools-gateway/routers/src/lib.rs:257]: The above call to `transact_through_sovereign` returns a normal `DispatchResult`, meaning that we cannot get the weight of the call. If there is another way of retrieving the weight of that call, please let me know and I will adjust.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 4]
```diff
@@ -56,6 +56,7 @@ impl<T: Config> From<RelayerMessageDecodingError> for Error<T> {
 pub mod pallet {
 	const BYTES_U32: usize = 4;
 	const BYTES_ACCOUNT_20: usize = 20;
+	const DEFAULT_WEIGHT_REF_TIME: u64 = 100_000_000;
```
Comment (cdamian) [inline pallets/liquidity-pools-gateway/src/lib.rs:59]: Please let me know if this value makes sense.

Comment (mustermeiszer) [reply pallets/liquidity-pools-gateway/src/lib.rs:59]: THat is equal to the weight of a single write. I think it should be a magnitude higher and times 5 maybe.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 5]
```diff
@@ -462,6 +501,66 @@ pub mod pallet {
...
+							error: e.error,
+						});
+
+						e.post_info
+					}
+				};
+
+				let weight = res
+					.actual_weight
+					.or(Some(Weight::from_parts(DEFAULT_WEIGHT_REF_TIME, 0)))
```
Comment (mustermeiszer) [inline pallets/liquidity-pools-gateway/src/lib.rs:548]: PoV weight is unfortunately not negligible here. The pov weight would at least be `MaxEnodedLen(T::Domain) + MaxEnodedLen(T::AccountId) + MaxEnodedLen(T::Message)` for each iterated item.

Comment (mustermeiszer) [reply pallets/liquidity-pools-gateway/src/lib.rs:548]: And this weight is always added. Not Matter if `actual_weight` is `Some` or not.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 6]
```diff
@@ -171,9 +191,24 @@ pub mod pallet {
...
+	/// Storage for outbound messages that will be processed during the
+	/// `on_idle` hook.
+	#[pallet::storage]
+	#[pallet::getter(fn outbound_message_queue)]
+	pub type OutboundMessageQueue<T: Config> = StorageNMap<
+		_,
+		(
+			NMapKey<Blake2_128Concat, Domain>,
+			NMapKey<Blake2_128Concat, T::AccountId>,
+			NMapKey<Blake2_128Concat, T::Message>,
```
Comment (mustermeiszer) [inline pallets/liquidity-pools-gateway/src/lib.rs:206]: This means, the same message will overwrite past once, but it should be possible to send the same message twice. We need ids unfortunately for the queue.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 7]
```diff
@@ -214,6 +246,13 @@ pub mod pallet {
 		RelayerMessageDecodingFailed { reason: RelayerMessageDecodingError },
 	}
 
+	#[pallet::hooks]
+	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
+		fn on_idle(_now: T::BlockNumber, max_weight: Weight) -> Weight {
+			Self::service_outbound_message_queue(max_weight)
+		}
```
Comment (mustermeiszer) [inline pallets/liquidity-pools-gateway/src/lib.rs:253]: Additionally I would add an extrinsic to progress a specific message manually inc ases the chain is busy.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 8]
```diff
@@ -485,13 +584,13 @@ pub mod pallet {
...
 			);
 
-			let router =
-				DomainRouters::<T>::get(destination.clone()).ok_or(Error::<T>::RouterNotFound)?;
-
-			router.send(T::Sender::get(), message.clone())?;
+			OutboundMessageQueue::<T>::insert(
+				(destination.clone(), T::Sender::get(), message.clone()),
+				(),
+			);
```
Comment (mustermeiszer) [inline pallets/liquidity-pools-gateway/src/lib.rs:590]: I would add the checks for missing routers here and fail in theses cases.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 9]
```diff
@@ -462,6 +501,66 @@ pub mod pallet {
...
+
+			for ((domain, sender, message), _) in OutboundMessageQueue::<T>::iter() {
+				processed_entries.push((domain.clone(), sender.clone(), message.clone()));
+
+				let router = match DomainRouters::<T>::get(domain.clone()) {
+					Some(router) => router,
+					None => {
+						Self::deposit_event(Event::RouterNotFound {
+							domain: domain.clone(),
+						});
```
Comment (mustermeiszer) [inline pallets/liquidity-pools-gateway/src/lib.rs:518]: If this error occurs, the message should be stored in an error storage with the problem that happened, or we we stop processing.

Comment (mustermeiszer) [reply pallets/liquidity-pools-gateway/src/lib.rs:518]: If we check the router when submitting, this would mean that intermediately, the router has been removed, but still state changes on Centrifuge Chain happened. So an error storage is the best IMO.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 10]
```diff
@@ -462,6 +501,66 @@ pub mod pallet {
...
+
+						r
+					}
+					Err(e) => {
+						Self::deposit_event(Event::RouterExecutionFailure {
+							sender: sender.clone(),
+							domain: domain.clone(),
+							message: message.clone(),
+							error: e.error,
+						});
```
Comment (mustermeiszer) [inline pallets/liquidity-pools-gateway/src/lib.rs:540]: Also an error storage would be best IMO.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 11]
```diff
@@ -462,6 +501,66 @@ pub mod pallet {
...
+				if weight_used.all_gte(max_weight) {
+					break;
+				}
+			}
+
+			for entry in processed_entries {
+				OutboundMessageQueue::<T>::remove(entry);
+			}
+
+			weight_used
```
Comment (mustermeiszer) [inline pallets/liquidity-pools-gateway/src/lib.rs:562]: The weight also includes 1 read and 1 write per entry, which need to added in the for loop.

**Review by mustermeiszer — COMMENTED** [review]
First look.

**Comment by mustermeiszer** [comment]
once this is realeased: We have to re-execute https://axelarscan.io/gmp/0x15c33b374f44725927e0025a3e3b07ebb99bc844307e2563161df8de6a331ac4:11

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 7 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:290]: Added an extrinsic for that.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 11 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:695]: Updated the weights here.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 5 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs]: I updated all weight calculations here.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 6 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs]: Added a nonce for keeping track of each outbound/failed message.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 8 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs]: Done.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 9 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs]: Saving the error along with the message info in the `FailedOutboundMessages` storage.

**Review by mustermeiszer — COMMENTED** [review]
Logic looks good! Need to check the weights again in more detail. Probably need @wischli eyes on this too! 

Should we add anymore test? I would like to bring this into the next RU if possible.

**Comment by gpmayorga** [comment]
there was an error in the pipeline due to Gcloud permissions. It is fixed but it seems like Clippy is unhappy still

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 12]
```diff
@@ -462,6 +621,139 @@ pub mod pallet {
...
+							message,
+						});
+
+						weight = weight
+							.saturating_add(T::DbWeight::get().writes(1))
+							.saturating_add(
+								post_info
+									.actual_weight
+									.expect("expected message processing weight"),
+							);
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:656]: Two nits:
1. Cleaner way is to use `weight.saturating_accrue` 
2. The expect message is a bit verbose. Since expecting can panic and thus should generally not be used, I'd prefer to point to the `Ok(...)` match here either via comment or the expect message itself to make it explicit.
```suggestion
						weight.saturating_accrue(T::DbWeight::get().writes(1)
							.saturating_accrue(
								post_info
									.actual_weight
									.expect("Message processing success already ensured; qed"),
							);
```

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 13]
```diff
@@ -462,6 +621,139 @@ pub mod pallet {
...
+							(domain, sender, message, e.error),
+						);
+
+						weight = weight
+							.saturating_add(T::DbWeight::get().writes(2))
+							.saturating_add(
+								e.post_info
+									.actual_weight
+									.expect("expected message processing weight"),
+							);
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:678]: Nit: see above

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 14]
```diff
@@ -462,6 +621,139 @@ pub mod pallet {
...
+					}
+				}
+
+				weight_used = weight_used.saturating_add(weight);
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:682]: Nit: The match could directly return the processing `weight` such that we don't need to handle two mutable `weights`.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 15]
```diff
@@ -462,6 +621,139 @@ pub mod pallet {
...
+					Ok(post_info) => {
+						Self::deposit_event(Event::OutboundMessageExecutionSuccess {
+							nonce,
+							sender,
+							domain,
+							message,
+						});
+
+						weight = weight
+							.saturating_add(T::DbWeight::get().writes(1))
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:651]: CR: I suppose the `write` here refers to the removal of the entry. We also need to account for the read operation
```suggestion
							.saturating_add(T::DbWeight::get().reads_writes(1, 1))
```

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 16]
```diff
@@ -462,6 +621,139 @@ pub mod pallet {
...
+							error: e.error,
+						});
+
+						FailedOutboundMessages::<T>::insert(
+							nonce,
+							(domain, sender, message, e.error),
+						);
+
+						weight = weight
+							.saturating_add(T::DbWeight::get().writes(2))
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:673]: CR: Should factor in the read as well.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 11 above)
Comment (wischli) [reply pallets/liquidity-pools-gateway/src/lib.rs:695]: The weight for reading and removing should be already applied in the iteration. Assume we reach the max weight in the iteration, then we cannot remove the entry anymore. Wondering why we need to accrue by 1 write per entry here again?

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 17]
```diff
@@ -423,6 +499,89 @@ pub mod pallet {
...
+		pub fn process_outbound_message(
+			origin: OriginFor<T>,
+			nonce: T::OutboundMessageNonce,
+		) -> DispatchResult {
+			ensure_signed(origin)?;
+
+			let (domain, sender, message) =
+				OutboundMessageQueue::<T>::get(nonce).ok_or(Error::<T>::OutboundMessageNotFound)?;
+
+			OutboundMessageQueue::<T>::remove(nonce);
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:518]: Nit: Just `take`

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 18]
```diff
@@ -423,6 +499,89 @@ pub mod pallet {
...
+			match Self::process_message(domain.clone(), sender.clone(), message.clone()) {
+				Ok(_) => {
+					Self::deposit_event(Event::<T>::OutboundMessageExecutionSuccess {
+						nonce,
+						domain,
+						sender,
+						message,
+					});
+
+					FailedOutboundMessages::<T>::remove(nonce);
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:568]: Q: AFAICS, fault messages which fail to succeed will congest our `FailedOutboundMessages` storage because they cannot be removed. Is that desired for now to keep things simple?

cc @mustermeiszer

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 19]
```diff
@@ -462,6 +621,139 @@ pub mod pallet {
...
+		) -> Weight {
+			let pov_weight: u64 = (Domain::max_encoded_len()
+				+ T::AccountId::max_encoded_len()
+				+ T::Message::max_encoded_len())
+			.try_into()
+			.expect("can calculate outbound message POV weight");
+
+			router_call_weight
+				.or(Some(Weight::from_parts(DEFAULT_WEIGHT_REF_TIME, 0)))
+				.unwrap()
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:753]: Nit: 
```suggestion
				.unwrap_or(Weight::from_parts(DEFAULT_WEIGHT_REF_TIME, 0))
```

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 20]
```diff
@@ -485,13 +777,23 @@ pub mod pallet {
...
-			let router =
-				DomainRouters::<T>::get(destination.clone()).ok_or(Error::<T>::RouterNotFound)?;
+			ensure!(
+				DomainRouters::<T>::contains_key(destination.clone()),
+				Error::<T>::RouterNotFound
+			);
 
-			router.send(T::Sender::get(), message.clone())?;
+			<OutboundMessageNonceStore<T>>::try_mutate(|n| {
+				*n = n.ensure_add(T::OutboundMessageNonce::one())?;
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:786]: Nit: 
```suggestion
				*n.ensure_add_assign(T::OutboundMessageNonce::one())?;
```

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 21]
```diff
@@ -485,13 +777,23 @@ pub mod pallet {
...
+				Ok::<_, DispatchError>(())
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:787]: Nit: Could return `*n` here to not have to read the value again below

```suggestion
				Ok::<T:: OutboundMessageNonce, DispatchError>(*n)
```

**Review by wischli — COMMENTED** [review]
Looks really good and clean! I have one minor, pedantic change request for the weight calculation because we are introducing an inherent here were being correct is important.

Apart from that, sorry about the large list of nits which can be ignored 🫠

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 22]
```diff
@@ -56,6 +60,10 @@ impl<T: Config> From<RelayerMessageDecodingError> for Error<T> {
 pub mod pallet {
 	const BYTES_U32: usize = 4;
 	const BYTES_ACCOUNT_20: usize = 20;
+	const DEFAULT_WEIGHT_REF_TIME: u64 = 5_000_000_000;
```
[the remark this answers is not in the document]
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:63]: This conversation here - https://github.com/centrifuge/centrifuge-chain/pull/1696#discussion_r1456370592

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 15 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:651]: No, this `write` is for the event deposit operation. Any other weights should be added accordingly in `process_message`.

Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:651]: I did add the missing 1 read tho, thanks for catching that!

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 12 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:656]: `saturating_accrue` cannot be used like that since it's return is `()`. I suggest we keep the `add` as it is since it's easier to read imo.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 16 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:673]: Done. Thank you!

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 13 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:678]: I changed the error message slightly since this should never happen anyway.

File: runtime/altair/src/liquidity_pools.rs [hunk 23]
```diff
@@ -100,6 +100,7 @@ impl pallet_liquidity_pools_gateway::Config for Runtime {
 	type MaxIncomingMessageSize = MaxIncomingMessageSize;
 	type Message = LiquidityPoolsMessage;
 	type OriginRecovery = crate::LiquidityPoolsAxelarGateway;
+	type OutboundMessageNonce = u64;
```
[the remark this answers is not in the document]
Comment (cdamian) [reply runtime/altair/src/liquidity_pools.rs:103]: Completely forgot about that, thank you!

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 21 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:787]: Done.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 20 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:786]: Done.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 19 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:753]: Done.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 11 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:695]: That extra write was for the removal of the entry which was not accounted for in the iteration. That was changed now, PTAL.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 14 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:684]: Done.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 18 above)
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/lib.rs:566]: We could also add some extrinsics for removing these as long as there's an admin doing it. Please let us know what you think @mustermeiszer

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 22 above)
[the remark this answers is not in the document]
Comment (wischli) [reply pallets/liquidity-pools-gateway/src/lib.rs:63]: Nit: Could add that as a comment to the code :)

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 12 above)
Comment (wischli) [reply pallets/liquidity-pools-gateway/src/lib.rs]: Whatever you prefer. Of course we don't reassign when using `accrue` but just alter the mutable `weight` variable.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 24]
```diff
@@ -462,6 +619,140 @@ pub mod pallet {
...
+								message,
+							});
+
+							post_info
+								.actual_weight
+								.expect("Message processing success already ensured")
+								// Extra weight breakdown:
+								//
+								// 1 read for the outbound message
+								// 1 write for the event
```
Comment (wischli) [inline pallets/liquidity-pools-gateway/src/lib.rs:653]: Dispatching an event is much cheaper than performing a `write` operation. But we can certainly keep the `1 write` here to be defensive.

**Review by wischli — DISMISSED** [review]
Thanks a lot for adhering to my pedantic nit picks 🫶. We only need to discuss the missing cleanup possibility of failure-safe messages, which IMO does not have to be part of this PR.

File: pallets/liquidity-pools-gateway/src/lib.rs [hunk 25]
```diff
@@ -423,6 +504,87 @@ pub mod pallet {
...
+
+					Ok(())
+				}
+			}
+		}
+
+		/// Manually process a failed outbound message.
+		#[pallet::weight(T::WeightInfo::process_failed_outbound_message())]
+		#[pallet::call_index(7)]
+		pub fn process_failed_outbound_message(
```
Comment (cdamian) [inline pallets/liquidity-pools-gateway/src/lib.rs:553]: Note how we always return `Ok(())` here so that we can preserve the storage changes in case of errors.

File: pallets/liquidity-pools-gateway/src/lib.rs (hunk 22 above)
[the remark this answers is not in the document]
Comment (wischli) [reply pallets/liquidity-pools-gateway/src/lib.rs:68]: Thanks a lot for adding the context 🫶

**Review by wischli — APPROVED** [review]
Great test additions!

File: pallets/liquidity-pools-gateway/src/tests.rs [hunk 26]
```diff
@@ -835,26 +955,162 @@ mod outbound_queue_impl {
...
+			assert_ok!(LiquidityPoolsGateway::submit(
+				sender.clone(),
+				domain.clone(),
+				msg.clone()
+			));
+
+			let expected_nonce = OutboundMessageNonce::one();
+
+			let queue_entry = OutboundMessageQueue::<Runtime>::take(expected_nonce)
+				.expect("an entry is added to the queue");
```
[the remark this answers is not in the document]
Comment (cdamian) [reply pallets/liquidity-pools-gateway/src/tests.rs:1101]: No reason in particular, I'll change it to `get` to make this less confusing.

**Review by wischli — APPROVED** [review]
