### PR TITLE
Add fixed point custom rounding rate

### LINKED ISSUE #931: Custom Rounding for `Rate`
Implement a few methods for our custom `FixedPointNumber` type `Rate` in `runtime_common`, that allow us to choose a rounding preference from time to time. One important aspect here is, that we use `Rate` always behind a trait bound. Meaning we can not use non-trait methods. Hence, we must define a trait for this.

### Implementation Draft
```rust
// Not sure if we actually need FixedPointOperand as a super trait
pub trait FixedPointOperandExtension: FixedPointOperand {
       fn checked_mul_floor(&self, int: &Self::Inner) -> Option<Self::Inner>;

       fn checked_mul_ceil(&self, int: &Self::Inner) -> Option<Self::Inner>;

       fn saturating_mul_floor(&self, int: &Self::Inner) -> Self::Inner;

       fn saturating_mul_ceil(&self, int: &Self::Inner) -> Self::Inner;
}
```

### PR DESCRIPTION
**Pull request by thea-leake**
# Description

Adds fns for operations on fixed point numbers with fixed point operands with specified rounding preference to allow us to choose whether to use ceil or floor.

Fixes #931

### Addition of ExtendedFixedNumber trait
Addition of ExtendedFixedNumber trait and implementation for Rate

Adds floor/ceil and with_rounding functions for:
- checked & saturating mul & mul int
- checked & saturating div and div int
- checked & saturating from rational
- checked reciprocal
- saturating pow

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Addition of unit tests in progress

# Checklist:

- [x] I have added Rust doc comments to structs, enums, traits and functions
- [x] I have made corresponding changes to the documentation
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I rebased on the latest `main` branch

### CODE REVIEW

File: libs/types/src/fixed_point.rs [hunk 1]
```diff
@@ -85,6 +85,63 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
+
+	/// Checks multiplication and rounds precision with preference down
+	/// returns None if out of bounds
+	fn checked_mul_floor<N: FixedPointOperand>(self, int: N) -> Option<N> {
+		self.checked_mul_round_pref(int, SignedRounding::NearestPrefLow)
+	}
+
+	/// Checks multiplication and rounds precision with preference up
+	/// returns None if out of bounds
+	fn checked_mul_ciel<N: FixedPointOperand>(self, int: N) -> Option<N> {
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:125]: typo ^^

**Review by mustermeiszer — COMMENTED** [review]
Looks already good! What do think about the macro? Do we wanna remove it?

File: libs/types/src/fixed_point.rs (hunk 1 above)
Comment (thea-leake) [reply libs/types/src/fixed_point.rs]: thanks, fixed

**Comment by thea-leake** [comment]
> Looks already good! What do think about the macro? Do we wanna remove it?

@mustermeiszer  Yeah, I've just pushed a commit to remove it.

File: libs/types/src/fixed_point.rs [hunk 2]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
 
-		impl ops::Mul for $name {
-			type Output = Self;
+	/// Checked multiplication for integer type `N`. Equal to `self * n`.
+	///
+	/// Returns `None` if the result does not fit in `N`.
+	fn checked_mul_int<N: FixedPointOperand>(self, n: N) -> Option<N> {
+		self.checked_mul_int_floor(n)
+	}
+}
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:293]: Same as above.

File: libs/types/src/fixed_point.rs [hunk 3]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
+		self.0.checked_add(rhs.0).map(Self)
+	}
+}
 
-			fn min() -> $name {
-				$name::min_value()
-			}
+impl CheckedDiv for Rate {
+	fn checked_div(&self, other: &Self) -> Option<Self> {
+		self.checked_div_floor(other)
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:447]: Same as above. If not explicitly used, I would like to have the current `NearestPrefLow` as default.

File: libs/types/src/fixed_point.rs [hunk 4]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
+	/// Checks multiplication and rounds precision with preference down
+	/// returns None if out of bounds
+	fn checked_mul_int_floor<N: FixedPointOperand>(self, int: N) -> Option<N> {
+		self.checked_mul_int_round_pref(int, SignedRounding::NearestPrefLow)
+	}
+
+	/// Checks multiplication and rounds precision with preference up
+	/// returns None if out of bounds
+	fn checked_mul_int_ceil<N: FixedPointOperand>(self, int: N) -> Option<N> {
+		self.checked_mul_int_round_pref(int, SignedRounding::NearestPrefHigh)
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:126]: This is not correct: Should be `SignedRounding::Major`

File: libs/types/src/fixed_point.rs [hunk 5]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
-					d.value,
-					Rounding::from_signed(SignedRounding::NearestPrefLow, negative),
-				)
-				.and_then(|value| from_i129(I129 { value, negative }))
-				.map(Self::from_inner)
-			}
+	/// Checks multiplication of val with FixedPoint and rounds precision down
+	/// Returns None if out of bounds
+	fn checked_mul_floor(&self, other: &Self) -> Option<Self> {
+		self.checked_mul_with_pref(other, SignedRounding::NearestPrefLow)
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:192]: This is not correct: Should be `SignedRounding::Mino`

File: libs/types/src/fixed_point.rs [hunk 6]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
-					Self::DIV.unique_saturated_into(),
-					Rounding::from_signed(SignedRounding::NearestPrefLow, negative),
-				)
-				.and_then(|value| from_i129(I129 { value, negative }))
-			}
-		}
+	/// Checks multiplication of val with FixedPoint and rounds precision up
+	/// Returns None if out of bounds
+	fn checked_mul_ceil(&self, other: &Self) -> Option<Self> {
+		self.checked_mul_with_pref(other, SignedRounding::NearestPrefHigh)
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:198]: This is not correct: Should be `SignedRounding::Major`

File: libs/types/src/fixed_point.rs [hunk 7]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
+	fn saturating_mul_with_pref(self, other: Self, r: SignedRounding) -> Self;
 
-			#[cfg(any(feature = "std", test))]
-			pub fn from_float(x: f64) -> Self {
-				Self((x * (<Self as FixedPointNumber>::DIV as f64)) as $inner_type)
-			}
+	/// Checks multiplication and rounds precision down
+	/// saturates if result out of bounds
+	fn saturating_mul_floor(self, other: Self) -> Self {
+		self.saturating_mul_with_pref(other, SignedRounding::NearestPrefLow)
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:208]: This is not correct: Should be `SignedRounding::Minor`

File: libs/types/src/fixed_point.rs [hunk 8]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
+	}
 
-			fn saturating_mul(self, rhs: Self) -> Self {
-				self.checked_mul(&rhs)
-					.unwrap_or_else(|| to_bound(self.0, rhs.0))
-			}
+	/// Checks divtiplication of val with FixedPoint and rounds precision up
+	/// Returns None if out of bounds
+	fn checked_div_ceil(&self, other: &Self) -> Option<Self> {
+		self.checked_div_with_pref(other, SignedRounding::NearestPrefHigh)
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:230]: This is not correct: Should be `SignedRounding::Major`

File: libs/types/src/fixed_point.rs [hunk 9]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
+	/// Returns None if out of bounds
+	fn checked_div_with_pref(&self, other: &Self, r: SignedRounding) -> Option<Self>;
 
-			fn saturating_sub(self, rhs: Self) -> Self {
-				Self(self.0.saturating_sub(rhs.0))
-			}
+	/// Checks divtiplication of val with FixedPoint and rounds precision down
+	/// Returns None if out of bounds
+	fn checked_div_floor(&self, other: &Self) -> Option<Self> {
+		self.checked_div_with_pref(other, SignedRounding::NearestPrefLow)
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:224]: This is not correct: Should be `SignedRounding::Minor`

File: libs/types/src/fixed_point.rs [hunk 10]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
 
-			#[cfg(any(feature = "std", test))]
-			pub fn to_float(self) -> f64 {
-				self.0 as f64 / <Self as FixedPointNumber>::DIV as f64
-			}
-		}
+	/// Checks multiplication and rounds precision up
+	/// saturates if result out of bounds
+	fn saturating_mul_ciel(self, other: Self) -> Self {
+		self.saturating_mul_with_pref(other, SignedRounding::NearestPrefHigh)
```
Comment (mustermeiszer) [inline libs/types/src/fixed_point.rs:214]: This is not correct: Should be `SignedRounding::Major`

**Review by mustermeiszer — COMMENTED** [review]
First look.

File: libs/types/src/fixed_point.rs [hunk 11]
```diff
@@ -85,1511 +85,1673 @@ fn to_bound<N: FixedPointOperand, D: FixedPointOperand, R: Bounded>(n: N, m: D)
...
+
+		multiply_by_rational_with_rounding(
+			lhs.value,
+			Self::DIV as u128,
+			rhs.value,
+			Rounding::from_signed(r, negative),
+		)
+		.and_then(|value| from_i129(I129 { value, negative }))
+		.map(Self)
+	}
```
[the remark this answers is not in the document]
Comment (thea-leake) [reply libs/types/src/fixed_point.rs:330]: If I remember right I removed the default implementation due to fields implemented on Rate that were being used.  I had some concerns with safety regarding bounds with a generic implementation.

Taking a look again at making a default implementation; I'd also prefer it to be a default implementation.

[the remark this answers is not in the document]
Comment (mustermeiszer) [reply libs/types/src/fixed_point.rs:330]: Ah you are right. Did not think about this.

**Review by mustermeiszer — COMMENTED** [review]
Just some minor stuff and nitpicks. Looks really good and neat!!

**Review by mustermeiszer — DISMISSED** [review]
I think we can merge this as is. The code is clean and super well tested. My only mention was a space in the docs, which is not important. We need this to be in for pallet-investments, so I would bring this in now! 

Thanks @thea-leake, that's really great to have now!

**Review by mustermeiszer — DISMISSED** [review]
Approving after Squash.

**Comment by thea-leake** [comment]
The prev squash wasn't signed correctly, amended with signature.

**Review by mustermeiszer — APPROVED** [review]
Approve after signed squash.
